-- ====================================================================
-- INE Product Price Tracker: Add scrape_runs table
-- Run this in the Supabase SQL Editor
-- ====================================================================

-- 4. SCRAPE RUNS TABLE
-- One row per cron/manual invocation. Groups all per-product scrape logs.
CREATE TABLE IF NOT EXISTS scrape_runs (
    id TEXT PRIMARY KEY,                         -- UUID string generated by backend
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at TIMESTAMPTZ,
    status VARCHAR(20) NOT NULL DEFAULT 'RUNNING', -- 'RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED'
    total_products INT DEFAULT 0,
    successes INT DEFAULT 0,
    failures INT DEFAULT 0,
    triggered_by VARCHAR(20) DEFAULT 'cron',      -- 'cron' or 'manual'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Grant access to service_role
GRANT ALL ON TABLE public.scrape_runs TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO service_role;

-- RLS
ALTER TABLE public.scrape_runs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service_role_all_scrape_runs" ON public.scrape_runs;
CREATE POLICY "service_role_all_scrape_runs"
ON public.scrape_runs
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- Performance index
CREATE INDEX IF NOT EXISTS idx_scrape_runs_status ON scrape_runs(status);
CREATE INDEX IF NOT EXISTS idx_scrape_runs_started_at ON scrape_runs(started_at DESC);

-- Also add scrape_run_id column to scrape_logs if not already present
-- (This links each log entry back to its run)
ALTER TABLE public.scrape_logs ADD COLUMN IF NOT EXISTS scrape_run_id TEXT REFERENCES scrape_runs(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_scrape_logs_run ON scrape_logs(scrape_run_id);
